import Foundation

private let claudeIdleFrame1: [[P]] = sprite([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".....OOOOOO.....",
    "....OWWWWWWO....",
    "...OWWWWWWWWO...",
    "...OWWEWWEWWO...",
    "...OWWWWWWWWO...",
    "...OWWSSSSWWO...",
    "...OWWSSSSWWO...",
    "...OWWWWWWWWO...",
    "....OWWWWWWO....",
    "....W.W.W.W.....",
])

private let claudeIdleFrame2: [[P]] = sprite([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".....OOOOOO.....",
    "....OWWWWWWO....",
    "...OWWWWWWWWO...",
    "...OWWEWWEWWO...",
    "...OWWWWWWWWO...",
    "...OWWSSSSWWO...",
    "...OWWSSSSWWO...",
    "...OWWWWWWWWO...",
    "....OWWWWWWO....",
    "....W.W.W.W.....",
])

private let claudeIdleFrame3: [[P]] = sprite([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "......OOOOOO....",
    ".....OWWWWWWO...",
    "....OWWWWWWWWO..",
    "....OWWEWWEWWO..",
    "....OWWWWWWWWO..",
    "....OWWSSSSWWO..",
    "....OWWSSSSWWO..",
    "....OWWWWWWWWO..",
    ".....OWWWWWWO...",
    ".....W.W.W.W....",
])

private let claudeWorkFrame1: [[P]] = sprite([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".....OOOOOO.....",
    "....OWWWWWWO....",
    "...OWWWWWWWWO...",
    "...OWWEWWEWWO...",
    "...OWWWWWWWWO...",
    "...OWWSSSSWWO...",
    "...OWWSSSSWWO...",
    "...OWWWWWWWWO...",
    "....OWWWWWWO....",
    "....W.W.W.W.....",
])

private let claudeWorkFrame2: [[P]] = sprite([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".....OOOOOO.....",
    "....OWWWWWWO....",
    "...OWWWWWWWWO...",
    "...OWWEWWEWWO...",
    "...OWWWWWWWWO...",
    "...OWWSSSSWWO...",
    "...OWWSSSSWWO...",
    "...OWWWWWWWWO...",
    "....OWWWWWWO....",
    "....W.W.W.W.....",
])

private let claudeWorkFrame3: [[P]] = sprite([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "......OOOOOO....",
    ".....OWWWWWWO...",
    "....OWWWWWWWWO..",
    "....OWWEWWEWWO..",
    "....OWWWWWWWWO..",
    "....OWWSSSSWWO..",
    "....OWWSSSSWWO..",
    "....OWWWWWWWWO..",
    ".....OWWWWWWO...",
    ".....W.W.W.W....",
])

private let claudeDoneFrame1: [[P]] = sprite([
    "..................",
    "..........BBBBB...",
    ".........BQQQQQB..",
    ".........BQQBQQB..",
    ".........BQQBQQB..",
    ".........BQQQQQB..",
    ".........BQQBQQB..",
    ".........BQQQQQB..",
    "..........BBQBB...",
    ".....OOOOOO.......",
    "....OWWWWWWO......",
    "...OWWWWWWWWO.....",
    "...OWWEWWEWWO.....",
    "...OWWWWWWWWO.....",
    "...OWWSSSSWWO.....",
    "...OWWSSSSWWO.....",
    "...OWWWWWWWWO.....",
    "....OWWWWWWO......",
    "....W.W.W.W.......",
])

private let claudeDoneFrame2: [[P]] = sprite([
    "..................",
    "...........BBBBB..",
    "..........BQQQQQB.",
    "..........BQQBQQB.",
    "..........BQQBQQB.",
    "..........BQQQQQB.",
    "..........BQQBQQB.",
    "..........BQQQQQB.",
    "...........BBQBB..",
    ".....OOOOOO.......",
    "....OWWWWWWO......",
    "...OWWWWWWWWO.....",
    "...OWWEWWEWWO.....",
    "...OWWWWWWWWO.....",
    "...OWWSSSSWWO.....",
    "...OWWSSSSWWO.....",
    "...OWWWWWWWWO.....",
    "....OWWWWWWO......",
    "....W.W.W.W.......",
])

private let claudeDoneFrame3: [[P]] = sprite([
    "..................",
    ".........BBBBB....",
    "........BQQQQQB...",
    "........BQQBQQB...",
    "........BQQBQQB...",
    "........BQQQQQB...",
    "........BQQBQQB...",
    "........BQQQQQB...",
    ".........BBQBB....",
    ".....OOOOOO.......",
    "....OWWWWWWO......",
    "...OWWWWWWWWO.....",
    "...OWWEWWEWWO.....",
    "...OWWWWWWWWO.....",
    "...OWWSSSSWWO.....",
    "...OWWSSSSWWO.....",
    "...OWWWWWWWWO.....",
    "....OWWWWWWO......",
    "....W.W.W.W.......",
])

let claudeSpriteSpec = ToolSpriteSpec(
    idle: [claudeIdleFrame1, claudeIdleFrame2, claudeIdleFrame3],
    work: [claudeWorkFrame1, claudeWorkFrame2, claudeWorkFrame3],
    done: [claudeDoneFrame1, claudeDoneFrame2, claudeDoneFrame3]
)
