import Foundation

private let codexIdleFrame1: [[P]] = sprite([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".....NNNNNN.....",
    "....NNCCCCNN....",
    "...NNCCAACCNN...",
    "..NNCA.EE.ACNN..",
    "..NCC......CCN..",
    "..NCC..EEE.CCN..",
    "..NCGGGGGGGGCN..",
    "..NCAAGGGGAACN..",
    "...NAA....AAN...",
    ".....a....a.....",
    "......gggg......",
])

private let codexIdleFrame2: [[P]] = sprite([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".....NNNNNN.....",
    "....NNCCCCNN....",
    "...NNCCAACCNN...",
    "..NNCA.EE.ACNN..",
    "..NCC......CCN..",
    "..NCC..EEE.CCN..",
    "..NCGGGGGGGGCN..",
    "..NCAAGGGGAACN..",
    "...NAA....AAN...",
    ".....a....a.....",
    "......gggg......",
])

private let codexIdleFrame3: [[P]] = sprite([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "......NNNNNN....",
    ".....NNCCCCNN...",
    "....NNCCAACCNN..",
    "...NNCA.EE.ACNN.",
    "...NCC......CCN.",
    "...NCC..EEE.CCN.",
    "...NCGGGGGGGGCN.",
    "...NCAAGGGGAACN.",
    "....NAA....AAN..",
    "......a....a....",
    ".......gggg.....",
])

private let codexWorkFrame1: [[P]] = sprite([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".....NNNNNN.....",
    "....NNCCCCNN....",
    "...NNCCAACCNN...",
    "..NNCA.EE.ACNN..",
    "..NCC......CCN..",
    "..NCC..EEE.CCN..",
    "..NCGGGGGGGGCN..",
    "..NCAAGGGGAACN..",
    "...NAA....AAN...",
    ".....a....a.....",
    "......gggg......",
])

private let codexWorkFrame2: [[P]] = sprite([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".....NNNNNN.....",
    "....NNCCCCNN....",
    "...NNCCAACCNN...",
    "..NNCA.EE.ACNN..",
    "..NCC......CCN..",
    "..NCC..EEE.CCN..",
    "..NCGGGGGGGGCN..",
    "..NCAAGGGGAACN..",
    "...NAA....AAN...",
    ".....a....a.....",
    "......gggg......",
])

private let codexWorkFrame3: [[P]] = sprite([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "......NNNNNN....",
    ".....NNCCCCNN...",
    "....NNCCAACCNN..",
    "...NNCA.EE.ACNN.",
    "...NCC......CCN.",
    "...NCC..EEE.CCN.",
    "...NCGGGGGGGGCN.",
    "...NCAAGGGGAACN.",
    "....NAA....AAN..",
    "......a....a....",
    ".......gggg.....",
])

private let codexDoneFrame1: [[P]] = sprite([
    "..........BBBBB...",
    ".........BQQQQQB..",
    ".........BQQBQQB..",
    ".........BQQBQQB..",
    ".........BQQQQQB..",
    ".........BQQBQQB..",
    ".........BQQQQQB..",
    "..........BBQBB...",
    ".....NNNNNN.......",
    "....NNCCCCNN......",
    "...NNCCAACCNN.....",
    "..NNCA.EE.ACNN....",
    "..NCC......CCN....",
    "..NCC..EEE.CCN....",
    "..NCGGGGGGGGCN....",
    "..NCAAGGGGAACN....",
    "...NAA....AAN.....",
    ".....a....a.......",
    "......gggg........",
])

private let codexDoneFrame2: [[P]] = sprite([
    "...........BBBBB..",
    "..........BQQQQQB.",
    "..........BQQBQQB.",
    "..........BQQBQQB.",
    "..........BQQQQQB.",
    "..........BQQBQQB.",
    "..........BQQQQQB.",
    "...........BBQBB..",
    ".....NNNNNN.......",
    "....NNCCCCNN......",
    "...NNCCAACCNN.....",
    "..NNCA.EE.ACNN....",
    "..NCC......CCN....",
    "..NCC..EEE.CCN....",
    "..NCGGGGGGGGCN....",
    "..NCAAGGGGAACN....",
    "...NAA....AAN.....",
    ".....a....a.......",
    "......gggg........",
])

private let codexDoneFrame3: [[P]] = sprite([
    ".........BBBBB....",
    "........BQQQQQB...",
    "........BQQBQQB...",
    "........BQQBQQB...",
    "........BQQQQQB...",
    "........BQQBQQB...",
    "........BQQQQQB...",
    ".........BBQBB....",
    ".....NNNNNN.......",
    "....NNCCCCNN......",
    "...NNCCAACCNN.....",
    "..NNCA.EE.ACNN....",
    "..NCC......CCN....",
    "..NCC..EEE.CCN....",
    "..NCGGGGGGGGCN....",
    "..NCAAGGGGAACN....",
    "...NAA....AAN.....",
    ".....a....a.......",
    "......gggg........",
])

let codexSpriteSpec = ToolSpriteSpec(
    idle: [codexIdleFrame1, codexIdleFrame2, codexIdleFrame3],
    work: [codexWorkFrame1, codexWorkFrame2, codexWorkFrame3],
    done: [codexDoneFrame1, codexDoneFrame2, codexDoneFrame3]
)
